add rpm packaging
d33d33/beamium-packages pull request #2
Opened 2017-03-02 15:52 UTC by gregleroux

2017-03-07 17:29 UTC, d33d33 requested changes

2017-03-07 17:29 UTC, d33d33 commented on Makefile
> +		  --description "Prometheus to Warp10 metrics forwarder" \
indent ;)

2017-03-10 13:50 UTC, gregleroux commented
indentation fixed on Makefile

2017-03-30 13:49 UTC, d33d33 approved these changes

2017-03-30 13:49 UTC, merged